apiVersion: apps/v1
kind: Deployment
metadata:
    name: goweb-deployment
spec:
    selector:
        matchLabels:
            app: goweb
    replicas: 3
    template:
        metadata:
            labels:
                app: goweb
        spec:
            containers:
            - name: goweb
              image: wangzz2017/web
              ports:
              - containerPort: 1323





